const AT = {
    GET_AUTO_COMPLETE_SUCCESS: 'GET_AUTO_COMPLETE_SUCCESS',
    GET_CURRENT_WEATHER_SUCCESS: 'GET_CURRENT_WEATHER_SUCCESS',
    GET_FIVE_DAY_WEATHER_SUCCESS: 'GET_FIVE_DAY_WEATHER_SUCCESS',
    ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
    REM_FROM_FAV: 'REM_FROM_FAV',
    FAIL_MSG: 'FAIL_MSG',
    EDIT_CURRENT_CITY: 'EDIT_CURRENT_CITY',
    LINK: 'http://dataservice.accuweather.com/',
    API_KEY: 'Neijlcq5HWIG9whwUgzP2AvRyRQ0fnz3',
    API_KEY1: 'qAWasab5si6MYD64DQvLIDF9fhP3qVKb',
    API_KEY2:'fAGGXfz6C130ttIiFZLGBZXBqzjFZwlA'
}

export default AT;